[workspace]
members = [
    "motor",
    "dc_motor",
    "encoder",
    "rotary_encoder",
    "wheel",
    "servo",
    "chassis",
    "gyro",
    "itg3205",
    "drawers_controller",
    "main"
]

[profile.dev]
debug = true

[profile.release]
codegen-units = 1
debug = true
lto = true

