[workspace]
members = [
    "motor",
    "dc_motor",
    "encoder",
    "rotary_encoder",
    "wheel",
    "wheel_position_controller",
    "main"
]

[profile.dev]
debug = true

[profile.release]
codegen-units = 1
debug = true
lto = true

